name: Provision S3 Bucket

on:
  push:
    branches:
      - feature/demo  # or the branch you want to trigger the workflow

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # specify your desired region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Run Terraform initialize
        working-directory: ./terraform
        run: terraform init

      - name: Run Terraform pan
        working-directory: ./terraform
        run: terraform plan --var-file"vars/test.tfvars"

      - name: Run Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve --var-file"vars/test.tfvars"

